version: 0.0
os: linux
files:
  - source: /
    destination: /usr/code/reviewer/
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: scripts/build.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20
      runas: ec2-user