# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
