# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reviews', '0002_auto_20161208_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
            preserve_default=False,
        ),
    ]
